Print("exercise 1")
user_text = input("Enter some text: ")
print(user_text)

print("exercise 2")
user_number = input("enter a number: ")
user_int = int(user_number)
print(user_int + 1)

print("exercise 3")
user_float = input("enter a number: ")
string_to_float = float(user_float)
print(string_to_float + .5)

print("exercise 4")
float_1 = input("enter a number: ")
float_2 = input("enter another number: ")
num1 = float(float_1)
num2 = float(float_2)
print(f'total added = {num1 + num2}')

print("exercise 5")
float_3 = input("enter a number: ")
float_4 = input("enter another number: ")
num3 = float(float_3)
num4 = float(float_4)
print(f'total multiplied is {num3 * num4}')

print("exercise 6")
int_1 = input("enter a number: ")
int_2 = input("enter another number: ")
num_5 = int(int_1)
num_6 = int(int_2)
print(f'total divided is {num_5 // num_6}')
